prompt = {'Reference number of Data in Exp group:',...
    'Enter the folder of Masks for the Data:',...
    'Enter the matlab file of Data timeline:',...
    'Enter the scan rate of cyclic voltammetry (mV):',...
    'Save route:'};

dlg_title = 'Input';
num_lines = 1;

defaultans = {'A1',...
    'G:\TaS2\20190318_TaS2_AFM_CH18SH\MaskA1',...
    'G:\TaS2\20190318_TaS2_AFM_CH18SH\matlab_data\A1.mat',...
    '100',...
    'G:\TaS2\20190318_TaS2_AFM_CH18SH\result'}; 

answer = inputdlg(prompt, dlg_title, num_lines, defaultans);
expName = answer{1};
maskPath = answer{2}; 
loader = answer{3};
rate = str2num(answer{4});
saveRoute = answer{5};

TaS2(expName, maskPath, loader, rate, saveRoute);
